dist: bionic

language: python

python:
  - 3.7
  - 3.8

install:
  - pip install plotly pandas
  - python setup.py install

before_script:
  - pip install pytest pytest-cov codecov

script:
  - pytest -v --cov-config=.coveragerc

after_success:
  - codecov
