name: blueBooby
channels:
  - conda-forge
dependencies:
    - python=3
    - numpy
    - scipy
    - matplotlib
    - setuptools
    - jupyterlab
    - pandas
    - gym
    - dash
    - plotly
    - pip:
      - pytest
